services:

  config-server:
    build:
      context: .
      dockerfile: config-server/Dockerfile
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: native
      JAVA_OPTS: "-Xms64m -Xmx128m"
    deploy:
      resources:
        limits:
          memory: 200m
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O", "/dev/null", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      JAVA_OPTS: "-Xms64m -Xmx128m"
    deploy:
      resources:
        limits:
          memory: 200m
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O", "/dev/null", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      JAVA_OPTS: "-Xms64m -Xmx150m"
    deploy:
      resources:
        limits:
          memory: 220m
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      JAVA_OPTS: "-Xms64m -Xmx150m"
    deploy:
      resources:
        limits:
          memory: 220m
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      JAVA_OPTS: "-Xms64m -Xmx150m"
    deploy:
      resources:
        limits:
          memory: 220m
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy